### ISSUE TITLE
Performance & Memory Issue with DynamoDB Object Model

### ISSUE THREAD

**Issue by jasonwadsworth** [aws/aws-sdk-net#1061]
We started to see an issue with our services that use the DynamoDB SDK using the object model. The services are fine under low load, but when the load starts to increase (~1000 requests per minute across four instances) we see significant issues. These services are running in Docker containers using .Net Core 2.1.3 (we've seen the issue with .Net Core 1.1 as well).

## Expected Behavior
Calls to DynamoDB perform at a much higher scale.

## Current Behavior
The calls to DynamoDB start to slow and the service eventually begins to timeout, causing the instance to fail and be replaced.

## Steps to Reproduce (for bugs)
We were able to reproduce this with a pretty simple service. The API was a simple GET endpoint that did a DynamoDB query on a hash key and returned the results. The record count was, on average, about 15 records, with a max of about 30. Records are not particularly big, well under 1k each. The key is using the object model. We were able to switch to the basic DynamoDB request model and see no issues. We were able to sustain loads of over 6000 requests per minute with just two instances and saw no performance issues at all.

## Context
The primary issue is that we end up with a significant number of failed requests. We have been able to mitigate this in one service by not using the object model, but have concerns that other services will start to see this same behavior as load increases.

## Your Environment
Docker container running an ASP .Net Core service. We've used different base Docker images with the same result.

One thing that is possibly worth mentioning is that we use the _TablePrefix_ option on all of our calls. 

## .NET Core Info
Both 1.1 and 2.1.3 for sure, likely an issue on any version.

**Comment by normj** [comment]
Can you let us know which version of AWSSDK.DynamoDbv2 you are using and also check in your projects deps.json file to see which version of AWSSDK.Core gets pulled in due to your AWS service dependencies.

Do you only notice this problem in Docker? What I'm trying to eliminate is if this is a problem specific to Linux or all platforms.

**Comment by jasonwadsworth** [comment]
AWSSDK.DynamoDBv2 version 3.3.8
AWSSDK.Core version 3.3.22.1

We are only running in Docker, so I don't know if the issue happens in Windows.

There is one other piece of information that may be helpful. We ran the Docker container with only a soft memory setting of 256MB, no hard limit. At times the memory would go through the roof, consuming upwards of 600% of the allocated memory. The container would become unresponsive at some point and the container would be replaced. Naturally the memory dropped at that point, but I was suspicious about garbage collection in that scenario. The memory didn't always spike like that before becoming unresponsive but it's possible the times when it didn't the container was on a host with less available memory.

**Comment by slang25** [comment]
This may have been fixed in DynamoDBv2 3.3.9.0 & AWSSDK.Core 3.3.24.0, [see here](https://github.com/aws/aws-sdk-net/blob/master/SDK.CHANGELOG.md#332960-2018-06-09-0101-utc).
There was an issue an issue with the async DocumentModel APIs, this looks pretty similar.

**Comment by jasonwadsworth** [comment]
I can test it with that version. I'm a little bit doubtful given that we have a service running, with similar to higher volume, that uses the DocumentModel and doesn't have any issues. I'll test it out with the newest version of the SDK and let you know if the problem persists.

**Comment by clearwaterstream** [comment]
I'm having the same issue. We are using DynamoDBv2 3.3.10.3 and ASP.NET Core 2.1.2 running on latest elastic beanstalk win platform as per (https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts.platforms.html#concepts.platforms.net)

We are running on .NET 4.7.2 full framework. With minor load of 6 hits per second the CPU on the machine will spike to 99%. No errors in the event log or any .NET errors. The odd thing is that the spike will occur say 4 or 5 minutes into the load test. All will be fine and all of a sudden you go from 2% CPU usage to 99%.

We are using the document model.

We've trying switching to Oracle RDS (just to rule out DynamoDB) and indeed no issues.

We'll do the update to the latest SDK and see if the issues go away.

**Comment by jasonwadsworth** [comment]
I have confirmed that the issue is still present with the latest SDK. 

AWSSDK.Core - 3.3.25.1
AWSSDK.DynamoDBv2 - 3.3.14

This does feel a lot like thread starvation, which could be an async problem. The API will not even respond to a request on a controller that just returns a 204 when it gets to the unstable state.

**Comment by clearwaterstream** [comment]
Same here. Upgraded to latest and greatest.

AWSSDK.Core - 3.3.25.1
AWSSDK.DynamoDBv2 - 3.3.14

One things to note: we are using document model, async, and we are using a single instance of AmazonDynamoDBClient. We are not creating and disposing the client on per-request basic b/c underneath we are assuming HttpClient is used and as per MS one should either use a singleton or the new HttpClientFactory.

I'll try disposing in per request basis to see if that helps ...

**Comment by clearwaterstream** [comment]
Found the issue in our case -- may not be related. But don't await GetNextSetAsync if you are in a loop. So no

`do {
 var items = await query.GetNextSetAsync();
} while (blah)`

this will eventually, under load, cause CPU to spike and perf to degrade. In this case, just do query.GetNextSet(); ....

**Comment by jasonwadsworth** [comment]
@clearwaterstream that's an interesting observation. I'm using the object model and the `QueryAsync<T>` method returns `AsyncSearch<T>`, which does not have a `GetNextSet`, only `GetNextSetAsync` and `GetRemainingAsync`. I'd be concerned that using `GetNextSet` would cause the thread to be blocked whilst reading the stream, which is not ideal.

**Comment by clearwaterstream** [comment]
@jasonwadsworth 

yeah, some AWS C# examples have you use GetNextSet() in a loop until query.IsDone. So what I do is

```
var table = Table.LoadTable(...);

var query = table.Query(new QueryOperationConfig(...));

var bucket = new List<item>(20); // 20 is our bucket or page size. After we fill it, we are good...

var i = 0;
do{
    i++;
    
    var items = query.GetNextSet();
    bucket.AddRange(items);

    if(query.PaginationToken == "{}")
        break; // there are no more records
} while (!query.IsDone || bucket.Count >= 20);
```
Since pagination is involved, we cannot simply do `query.GetRemaining();`

Here is what I found interesting. To fill a bucket that can contains 20 items, sometimes GetNextSet() gets called 17 times in that loop! Often `GetNextSet()` will return no items and yet the `query.IsDone` is false. On the next call to GetNextSet() in the loop iteration, there may be items returned. Very odd. With `IDataReader`, for example, you call `Read()` until there is nothing to read but each `Read()` call will yield an item. Not the case with `GetNextSet()`. Looks like it just returns chunks that may or may not have data.

So imagine if that loop called `GetNextSet()` 17 times using `async`. I think that would create a lot of context switching.

**Comment by jasonwadsworth** [comment]
If `GetNextSet()` or `GetNextSetAsync()` is returning empty sets but has another page that seems like a poor implementation. However, I'll take 17 context switches over a blocked thread making 17 HTTP requests.

**Comment by clearwaterstream** [comment]
Well that's where IIS + ASP.NET Core interaction comes into play. IIS has a certain queue depth, and once ASP.NET Core app switches into "i'm free to take work" state b/c it's `awaiting` something then IIS may start sending more requests into the app. Then the app switches out of the `awaiting`, only to find another request just landed. This could cause a high number of ungated requests being sent into the app.

The issue in the loop is that every time that loop runs, IIS will send multiple requests into the app as a result of a single request signaling that's it's free. Consider this flow: IIS lets in one request, that request starts the loop, switches context to "free" several times, IIS sends multiple other requests into the app, those requests in turn start signaling they are free from "the loop", and so the problem worsens until you are at 99% CPU.

This problem would not occur if your app handled different workflows but in our case our app pretty much does one thing and all flows go into "the loop".

Removing `await` allowed IIS to "hold back" requests in its queue prior to sending them into the app. Tricky business. But maybe unique to us as typically web apps handle multiple flows / scenarios at any given moment and async/await shines in that case ....

**Comment by jasonwadsworth** [comment]
@normj is this something that's being looked into? I need to understand how we need to move forward. If this is being looked into we can continue down our current path and hope for a fix. If it's not we need to have our teams use basic DynamoDB requests instead of the object model.

**Comment by niraj-bpsoftware** [comment]
Facing similar issue. We have lambda functions querying results from dynamodb that needs to be returned in a specific JSON format. Lambda functions are exposed through API Gateway endpoint so we have total 30 seconds to finish the work and provide result back to API Gateway.
What would be the best efficient way to load the query results with pagination? I suspect .NET Object and Document model is slower than the low level APIs. If I use low level API, I still need to convert it the required JSON model. 
Just wondering if any one's been there, done that?

**Comment by robvanpamel** [comment]
We are facing the same issue, is there already a workaround available at this moment ? The issue is still open...

**Comment by tmschlot** [comment]
@robvanpamel As far as I know, this is still an issue.  We ended up using the [Low-Level Interfaces](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.SDKs.Interfaces.LowLevel.html) for interacting with DynamoDB, because 1) we were using it in a couple of other places already for specific features and 2) it's reliable.

**Comment by robvanpamel** [comment]
Hi @tmschlot : As the issue seems to be related to `ThirdParty.Json.LitJson` , isnt this happening at the lower levels as well ?

**Comment by tmschlot** [comment]
That is a good point, @robvanpamel.  Your issue appears to happen when reading the stream to calculate the CRC.  That seems way more generic than just the DynamoDB package's Object Persistence Model code.  That makes me wonder whether what you're running into is the same problem as what was originally reported.  Maybe this is something new.

**Comment by normj** [comment]
I have been attempting to reproduce the issue with no success and would appreciate help creating a simple repo case that I can diagnose.

Here is the code I have been running in a Fargate container with the smallest settings and haven't seen memory increases or errors.
https://gist.github.com/normj/8c492950fc8e289a6a757760f91f89da

The code basically continually does a table scan and also uses a lot of tasks to do individual reads for each item in the table.

Any suggestions on how I can alter the code to reproduce a memory leak would be greatly appreciated.

**Comment by clearwaterstream** [comment]
@normj I've had this issue happen when using GetNextSetAsync() (as opposided to GetNextSet()) in a loop, when pagination is involved. Let me do a quick app where I'll seed a table, then we'll attempt to read it and hopefully see the CPU pegged at 99% when running a simple query with minimal load.

**Comment by normj** [comment]
To be clear in my case, I cranked up the number of tasks till the CPU was maxed out since there were comments earlier that this only happened when at high load.

**Comment by clearwaterstream** [comment]
@normj I just created a [test app](https://github.com/clearwaterstream/DynamoDb-cpu99-Issue/blob/master/src/DynamoDBCPU99/Application/Persistence/ZipCodeDb.cs) and a mock DynamoDB table with 1k ZipCode entries. I then run pagination queries against it, hoping to get "blank" sets when calling GetNextSet() and I did not encounter any blanks! I cannot repro the issue. I do not have access to the old source code (where I've encountered the issue) but it was definitely running against an older AWS SDK.

**Comment by clearwaterstream** [comment]
@normj Update: while organically I was not able to repro the issue, I was able to get a couple of blank sets by switching to Scan vs Query (same column and condition) and Limiting to 5 records. Since some of the sets were blank (or had 1 or 2 records), it caused more calls to `GetNextSetAsync()` until `query.IsDone` was `true` . I could not consistently repro this (even with `Limit` of 5). While reading https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Scan.html it made me think the reason why I was encountering this issue before was the record size. Under the "Limit" section it mentions that if the " if the processed dataset size exceeds 1 MB before DynamoDB reaches this limit, it stops the operation and returns the matching values up to the limit...".

**Comment by normj** [comment]
@clearwaterstream `GetNextSetAync` is expected to sometimes return no data but still not be done with the query causing you to have to call it again. I recognize coming from other data clients this is not intuitive but a major difference here is the calls are going of HTTP calls versus a dedicated socket connection like most database drivers. Eventually HTTP calls will timeout so when a query/scan call is made it will return after a certain of items in DDB have been read to see if they meet the criteria not how many items has it found that match the criteria. 

 @robvanpamel Your problem seems different because it is not a memory issue but an exhausted thread pool. Make sure you are using the at least version `3.3.9.0` as that includes work @slang25 contributes to reduce the amount of tasks used by the SDK when using async operations. If you are using a version `3.3.9` or later then we need more information about how you are calling the SDK, like async versus sync and are you using anything else that consumes threads. I would recommend opening a separate issue for Task starvation because this issue is created to look at the memory consumption issues of the SDK and that is what I'm looking into.

For those that are seeing an `OutOfMemoryException`, is it only happening when load reaches some high point? Is anybody seeing the issue when the load is at some medium load and overtime the memory creeps up and then throws `OutOfMemoryException`? I'm trying to distinguish if there is a memory leak or inefficient usage of memory causing `OutOfMemoryException` when too much memory is request to handle the current incoming level of requests.

**Comment by normj** [comment]
I have a container I have been running for quite awhile that exposes an HTTP endpoint to trigger a DynamoDB query like I have seen others here talk about. When I use my perf tool to push the CPU to about 85% the memory has stayed consistent.

![image](https://user-images.githubusercontent.com/1653751/64569506-83770c00-d312-11e9-9d43-b32807178ae4.png)

When I push the CPU to 9X% percent then I have seen the garbage collector in the container not be able to keep up and throw an out of memory exception. This appears to match what others have been saying that when CPU is maxed out things fall apart if they they are moderately high or below things are fine. 

This leads me to conclude we don't have a memory leak because if we did it would still crash at lower CPU just take longer. I believe the DDB high level library is inefficient with their memory usages but I don't think there is a quick solution to that other then rewrite the high level libraries. Most likely the inefficiency come from the layers Object Model uses. By that I mean a request going from the Object Model -> Document Model -> Service Client -> Document Model -> Object Model.

Does this match with what others are seeing?

.NET Core 3.0 coming out later this month has some new interesting settings that can be used to control the garbage collector to make it more aware of it's constraint container environment. That is also worth some investigation. https://devblogs.microsoft.com/dotnet/using-net-and-docker-together-dockercon-2019-update/. Has anybody tried these yet?

**Comment by klaytaybai** [comment]
Closing due to inactivity.  Please feel free to continue commenting.  We may reopen this at a later time.
